import React from 'react';
import { View } from 'react-native';
// Import from your LOCAL components folder generated by the CLI
import { Box } from '@/components/ui/box';
import { Text } from '@/components/ui/text';
import { Heading } from '@/components/ui/heading';
import { VStack } from '@/components/ui/vstack';
import { HStack } from '@/components/ui/hstack';
import { Center } from '@/components/ui/center';
import { Fab, FabIcon } from '@/components/ui/fab';
import { Icon, AddIcon, MenuIcon } from '@/components/ui/icon';

export default function Dashboard() {
  return (
    <Box className="flex-1 bg-black px-6 pt-16">
      {/* Header Area [cite: 161, 165] */}
      <HStack className="justify-between items-center mb-10">
         <Box>
          <Icon as={MenuIcon} size="xl" className="text-white" />
        </Box>
        <Heading className="text-white text-2xl font-bold">
          amidFly
        </Heading>
      </HStack>

      <Text className="text-gray-400 text-lg font-medium mb-20">
        My devices(0)
      </Text>

      <Center className="flex-1">
        <VStack space="md" className="items-center">
          <Box className="opacity-20">
             {/* Large icon acting as the drone illustration placeholder [cite: 163] */}
            <Icon as={AddIcon} className="w-24 h-24 text-gray-500" /> 
          </Box>
          <Text className="text-gray-500 text-base text-center">
            No devices have been added yet
          </Text>
        </VStack>
      </Center>


      <Fab
        size="lg"
        placement="bottom center"
        className="bg-gray-100 mb-10 rounded-full"
        onPress={() => console.log("Add Device")}
      >
        <FabIcon as={AddIcon} className="text-black w-8 h-8" />
      </Fab>
    </Box>
  );
}